_wandb:
    value:
        cli_version: 0.22.3
        e:
            7qglodie0qm9cosrc7i7zxiw108ixlee:
                codePath: run_random.py
                codePathLocal: run_random.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "490577010688"
                        used: "459901321216"
                email: carlo.romeo.alt427@gmail.com
                executable: /home/romeo/miniconda3/envs/speq/bin/python
                git:
                    commit: 3feef686b54506bf640dfddd43ccf79a7618d581
                    remote: https://github.com/CarloRomeo427/ARC.git
                gpu: NVIDIA GeForce RTX 2080 SUPER
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 3072
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080 SUPER
                      uuid: GPU-91e52658-79c5-4c5e-d8fa-a8ebfc8ae974
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070 SUPER
                      uuid: GPU-176994fc-3e1f-480d-47b4-b197cb2b585d
                host: Glados
                memory:
                    total: "33634131968"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.31
                program: /home/romeo/Projects/ARC/run_random.py
                python: CPython 3.11.14
                root: /home/romeo/Projects/ARC
                startedAt: "2026-02-04T21:36:24.558775Z"
                writerId: 7qglodie0qm9cosrc7i7zxiw108ixlee
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
lobby_size:
    value: 12
master_seed:
    value: 42
matchmaker:
    value: Random
num_episodes:
    value: 10000
num_players:
    value: 1200
raid_repetitions:
    value: 10
raids_per_episode:
    value: 100
